book_app/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = "book_app"

urlpatterns = [
	url(r"^login/$", 
			auth_views.LoginView.as_view(
				template_name="book_app/login.html",
			),
			name='login'),
    url(r"^logout/$", auth_views.LogoutView.as_view(
    		template_name="book_app/index.html"
    	), name="logout"),
    url(r'^register/$', views.Register.as_view(), name='register'),
    url(r'^book_table/(?P<pk>\d+)/$', views.BookTableView.as_view(), name='book_table'),
    url(r'^upload/$', views.UploadBookDataView.as_view(), name='upload'),
    url(r'^csv_list/$', views.CSVBookListView.as_view(), name='csv_list')
]

bookexplorer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from book_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^book_app/', include('book_app.urls', namespace='book_app')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class BookData(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, default=1)
	CSVName = models.CharField(max_length=25, unique=True)
	CSVURL = models.URLField(blank=True, null=True)
	upload = models.FileField(null=True, blank=True)

	def __str__(self):
		return self.CSVName

book_app/forms.py
import os
import io
import csv
import tempfile
import urllib
import requests
import uuid
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import BookData

class UserCreateForm(UserCreationForm):
	username = forms.EmailField()

	class Meta:
		fields = ("username", "password1", "password2")
		model = get_user_model()

	def __init__(self, *args, **kwargs):
		super(UserCreateForm, self).__init__(*args, **kwargs)
		self.fields["username"].label = "Username:"
		self.fields["username"].help_text = None
		self.fields["password1"].help_text = None
		self.fields["password2"].help_text = None


class BookDataForm(forms.ModelForm):
	user = forms.ModelChoiceField(widget = forms.HiddenInput(), queryset=User.objects.all())
	upload = forms.FileField(widget=forms.FileInput(attrs={'accept': ".csv"}))
	id_is_unique = True

	def clean_upload(self):
		csv_file = self.cleaned_data['upload']
		csv_file2 = self.cleaned_data['upload']
		
		counter1 = 0
		self.id_is_unique = True

		# print("Hello clean upload")
		# Nested loop to to check each row id is unique
		if csv_file:
			books_reader = csv.reader(csv_file, delimiter=str(u',').encode('utf-8'), quotechar=str(u'|').encode('utf-8'))
			# print("Hello csv file")

			if books_reader:
				# print("Hello book reader")

				
				for row1 in books_reader:
					counter1 = counter1 + 1
					# print("Hello row %s"%row1)

					
					if csv_file2:
						books_reader2 = csv.reader(csv_file2, delimiter=str(u',').encode('utf-8'), quotechar=str(u'|').encode('utf-8'))
						counter2 = 0
						# print("Hello csv_file2")

						
						for row2 in books_reader2:
							counter2 = counter2 + 1
							# print("Hello row2 %s"%row2)
							
							if counter1 != counter2:
								# print("Hello counter1 %s"%counter1)

								
								if row1[3] == row2[3]:
									self.id_is_unique = False
									raise forms.ValidationError("CSV file does not have a unique id's")
		
		# csv file size max 3KB
		if csv_file.size > 3000:
			raise forms.ValidationError("CSV file is too large")
		
		# csv colomn
		row_counter = 0
		if csv_file:
			col_books_reader = csv.reader(csv_file, delimiter=str(u',').encode('utf-8'), quotechar=str(u'|').encode('utf-8'))
			# print("Hello csv file")

			if col_books_reader:

				for book_row in col_books_reader:
					col_amount = len(book_row)
					print("Coloumn amount %s"%col_amount)

					if col_amount > 5 or col_amount < 5:
						raise forms.ValidationError("Wrong number of columns in csv file")				
	
		return csv_file

				

	class Meta:
		fields = ("user", "upload")
		model = BookData
	

book_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
import io
import csv
import tempfile
import urllib
import requests
import uuid
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseForbidden
from django.views.generic import (
									TemplateView, 
									DetailView,
									CreateView,
									UpdateView,
									DeleteView,
									ListView,
									FormView
								)
from . import models
from . import forms
from bookexplorer import settings


class Register(CreateView):
    form_class = forms.UserCreateForm
    template_name = "book_app/register.html"
    success_url = reverse_lazy("index")

class IndexView(TemplateView):
	template_name = 'book_app/index.html'

class BookTableView(DetailView):
	template_name = 'book_app/book_table.html'
	model = models.BookData

	def get_success_url(self):
		return reverse_lazy('book_app:book_table', kwargs={'pk': self.object.pk})

	def get_context_data(self, **kwargs):
		context = super(BookTableView, self).get_context_data(**kwargs)
		user = self.request.user
		book_obj = self.get_object()
		
		if user.is_authenticated:
			# get file name for title with uuid for uniqueness
			context['file_name'] = book_obj.upload.name
			book_data = self.readBookCSV(book_obj.upload)
			context['book_data'] = book_data
		return context
	

	def readBookCSV(self, csv_file):
		books = []
		books_reader = csv.reader(csv_file, delimiter=str(u',').encode('utf-8'), quotechar=str(u'|').encode('utf-8'))
		
		for row in books_reader:

			# book dict the data can be easily manipulated and put into a table
			book = {
				"book_title": row[0], 
				"book_author": row[1], 
				"date_published": row[2], 
				"book_ID": row[3], 
				"book_publisher": row[4] 
			}

			books.append(book)
		csv_file.close()

		return books

class CSVBookListView(ListView):
	template_name = 'book_app/book_list.html'
	model = models.BookData

	def get_context_data(self, **kwargs):
		context = super(CSVBookListView, self).get_context_data(**kwargs)
		user = self.request.user
		if user.is_authenticated:
			context['book_csv_list'] = models.BookData.objects.filter(user=user)
		return context


class UploadBookDataView(FormView):
	model = models.BookData
	form_class = forms.BookDataForm
	template_name = "book_app/create_book_data.html"
	
	def get_success_url(self):
		return reverse_lazy('book_app:book_table', kwargs={'pk': self.object.pk})

	def get_context_data(self, **kwargs):
		context = super(UploadBookDataView, self).get_context_data(**kwargs)
		user = self.request.user
		form = self.get_form()
		
		if user.is_authenticated:
			form.initial['user'] = user.id					
			context['book_form'] = form
		return context

	def post(self, request, *args, **kwargs):
		
		if not request.user.is_authenticated:
			return HttpResponseForbidden()

		form = self.get_form()
		
		if form.is_valid():
			return self.form_valid(form)
		else:
			return super(UploadBookDataView, self).form_invalid(form)

	def form_valid(self, form):
		id_is_unique = True
		book_form = form
		unique_name = "no_name"
		
		if book_form.is_valid():
			csv_file = book_form.cleaned_data.get('upload')

			# gen unique name using uuid
			new_uuid = uuid.uuid4().hex
			uuid_reduced = new_uuid[:8]
			str_len = len(csv_file.name)
			new_len = str_len - 4
			file_name = csv_file.name[:new_len]
			unique_name = '%s%s%s'%(file_name, uuid_reduced, ".csv")

			csv_file.name = unique_name

			# create bucket url
			bucket_url =  'https://%s.s3.%s.amazonaws.com/%s/'%(settings.AWS_STORAGE_BUCKET_NAME, settings.AWS_REGION_HOST, unique_name)	
				
		
		new_book_data = models.BookData(
			user = form.cleaned_data['user'],
			CSVName = unique_name,
			CSVURL = bucket_url,
			upload = csv_file
		)

		self.object = new_book_data
		new_book_data.save()
		if id_is_unique:
			return super(UploadBookDataView, self).form_valid(form)
		else:
			return super(UploadBookDataView, self).form_invalid(form)

	

templates/book_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>{% block title %}{% endblock %}</title>
  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
  <!-- Custom styles for this template -->
  <link href="{% static 'css/modern-business.css' %}" rel="stylesheet" />
  {% block templatecss %}{% endblock %}              
</head>

<body>
  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}">Book Explorer</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">
        </span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a name="home_nav" class="nav-link" href="{% url 'index' %}">HomePage</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a name="csv_list_nav" class="nav-link" href="{% url 'book_app:csv_list' %}">Book List</a>
            </li>
           <li class="nav-item">
            <a name="logout_nav" class="nav-link" href="{% url 'book_app:logout' %}">Logout</a>
            </li>
            {% block profile_nav %}{% endblock %}
          {% else %}
          <li class="nav-item">
            <a name="login_nav" class="nav-link" href="{% url 'book_app:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a name="register_nav" class="nav-link" href="{% url 'book_app:register' %}">Register</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    {% block content %}{% endblock %}
  </div>
  <!-- /.container -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>


</html>

templates/book_app/book_list.html
{% extends "book_app/base.html" %}
{% load static %}
{% block title %}Book CSV List{% endblock %}
{% block templatecss %}<link href="{% static 'css/book_list.css' %}" rel="stylesheet">{% endblock %}

{% block content %}
    <div>
    <a type="submit" class="btn btn-primary cat-list-button"  href="{% url 'book_app:upload' %}">Add Cat</a>
    </div>
    <!-- </div> -->
    <div class="cat-list-container">
      <ul class="my-4 cat-list-list">
        {% for csv in book_csv_list %}
        <li>
          <div class="cat-list-item">
            <div class="csv_name">
              <h3>{{ csv.CSVName }}</h3>
            </div>
            <a name="book_item_select" class="btn btn-primary cat-list-item-button" href="{% url 'book_app:book_table' pk=csv.pk %}">Go to Book Table</a> 
          </div>
        </li>
        {% endfor %}
      </ul>
    </div>
{% endblock %}

templates/book_app/book_table.html
{% extends "book_app/base.html" %}
{% load static %}
{% block title %}{{ file_name }}{% endblock %}
{% block templatecss %}<link href="{% static 'css/book_table.css' %}" rel="stylesheet" />{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    <h1>{{ file_name }}</h1>
    <table>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Published</th>
        <th>ID</th>
        <th>Publisher</th>
      </tr>
      {% if book_data %}
        {% for book in book_data %}
          <tr>
            <td>{{ book.book_title }}</td>
            <td>{{ book.book_author }}</td>
            <td>{{ book.date_published }}</td>
            <td>{{ book.book_ID }}</td>
            <td>{{ book.book_publisher }}</td>
          </tr>
        {% endfor %}
      {% endif %}
    </table>
  {% endif %}
{% endblock %}

templates/book_app/create_book_data.html
{% extends "book_app/base.html" %}
{% load static %}
{% block title %}Book Data Form{% endblock %}
{% block templatecss %}<link href="{% static 'css/create_book_data.css' %}" rel="stylesheet" />{% endblock %}
{% if user.is_authenticated %}
{% endif %}

{% block content %}
    <br>
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <div class="register-container">
            <p>{{ book_form.as_p }}</p>
            <button name="book_submit_btn" type="submit" class="btn btn-primary btn-btn">Submit</button>
        </div>
    </form>
    <br>
    <ul>
    	{% if book_form.errors %}
    		{% for field in book_form %}
        		{% for error in field.errors %}
            		<li class="alert alert-danger error_message">{{ error }}</li>    
        		{% endfor %}
        	{% endfor %}
        {% endif %}
    </ul>
{% endblock %}

templates/book_app/index.html
{% extends "book_app/base.html" %}
{% load static %}
{% block title %}Home Page{% endblock %}
{% block templatecss %}<link href="{% static 'css/style.css' %}" rel="stylesheet" />{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    <div class="jumbotron">
      <h1>Click here to go to upload page</h1>
      <a class="btn btn-primary" href="{% url 'book_app:upload' %}">Upload Page</a>
    </div>
  {% else %}
     <div class="jumbotron">
      <h1>Please Register</h1>
      <a class="btn btn-primary" href="{% url 'book_app:register' %}">Register Page</a>
    </div>
  {% endif %}
{% endblock %}

templates/book_app/login.html
{% extends "book_app/base.html" %}
{% load static %}
{% block title %}Login{% endblock %}
{% block templatecss %}<link href="{% static 'css/login.css' %}" rel="stylesheet" />{% endblock %}
{% block content %}
    <br>
    <form method="POST">
      {% csrf_token %}
      <div class="login-container">
        {{ form.as_p }}
        <input name="login_button" type="Submit" class="btn btn-success btn-btn" value="Log in" />
      </div>
      <div class="button-container">
          <span class="psw">Not a User?     <a href="{% url 'book_app:register' %}">Sign Up Here</a></span>
      </div>
    </form>
{% endblock %}

templates/book_app/register.html
{% extends "book_app/base.html" %}
{% load static %}
{% block title %}Profile Form{% endblock %}
{% block templatecss %}<link href="{% static 'css/register.css' %}" rel="stylesheet" />{% endblock %}
{% block content %}
   <br>
    <form method="POST">
      {% csrf_token %}
      <div class="register-container">
        {{ form.as_p }}
        <button name="reg_submit_btn" type="submit" class="btn btn-primary btn-btn">Register</button>
      </div>
      <div class="button-container">
          <span class="psw">Already a User?     <a href="{% url 'book_app:login' %}">Login Here</a></span>
      </div>
    </form>
    <br>
{% endblock %}